### ISSUE TITLE
Deprecated config in `setup.cfg`

### ISSUE THREAD

**Issue by tomer-ds** [saadmk11/changelog-ci#103] opened 2023-08-06 09:25 UTC
## Describe the bug
The action just stopped working one day...
Came to run changelog workflow in a repo where it exists already some months and the Docker step fails

## Your Environment

**Workflow Run URL (if Public Repository):**
(Example: `https://github.com/saadmk11/changelog-ci/actions/runs/1350256604`)
**Contents of Your Changelog-CI Workflow File (.yaml File):**

```yaml
name: Changelog CI

on:
  push:
    branches:
      - "release/**"
    paths-ignore:
      - "*.md"

  workflow_call:
  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: large-ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.12.0"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.1
        with:
          config_file: .github/config/changelog-config.yaml
          release_version: ${{ steps.gitversion.outputs.majorMinorPatch }}
          github_token: ${{ secrets.GITHUB_TOKEN  }}
```

**Contents of Changelog-CI Configuration File (If Applicable):**

```yaml
changelog_type: "pull_request"
header_prefix: "Version:"
commit_changelog: true
comment_changelog: false
include_unlabeled_changes: true
unlabeled_group_title: "Changes"
pull_request_title_regex: ".*"
version_regex: ".*"
group_config:
  - title: Grafana Agent
    labels:
      - grafana-agent
  - title: Grafana Agent Operator
    labels:
      - grafana-agent-operator
  - title: Grafana Mimir
    labels:
      - grafana-mimir
  - title: Kowl
    labels:
      - kowl
  - title: Kube Downscaler
    labels:
      - kube-downscaler
  - title: Kubecost
    labels:
      - kubecost
  - title: Lightstreamer
    labels:
      - lightstreamer
  - title: Lightstreamer Proxy
    labels:
      - lightstreamerproxy
  - title: mFas
    labels:
      - mfas
  - title: OM2 Application RBAC
    labels:
      - om2-app-rbac
  - title: OM2 Webserver
    labels:
      - om2-webserver
  - title: TOMS
    labels:
      - toms
  - title: Vault Template
    labels:
      - vault-template

```

## Expected behavior
Changelog should run and successfully generate changelog in PR against Release ranch.

## Actual behavior
Step fails during docker build due to `The license_file parameter is deprecated, use license_files instead.`

## Additional context

```
 ---> 8fab4e3a7bc3
  Step 10/14 : COPY ./requirements.txt .
   ---> c722923b71d1
  Step 11/14 : RUN pip install -r requirements.txt
   ---> Running in f134e2694a82
  Collecting PyYAML~=5.4.1
    Downloading PyYAML-5.4.1.tar.gz (175 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 KB 36.0 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [62 lines of output]
        /tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
        !!
        
                ********************************************************************************
                The license_file parameter is deprecated, use license_files instead.
        
                By 2023-Oct-30, you need to update your project and remove deprecated calls
                or your builds will no longer be supported.
        
                See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                ********************************************************************************
        
        !!
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        running egg_info
        writing lib3/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib3/PyYAML.egg-info/top_level.txt
        Traceback (most recent call last):
          File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 271, in <module>
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
            self.find_sources()
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
            mm.run()
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
          File "<string>", line 201, in get_source_files
          File "/tmp/pip-build-env-_i02_h0g/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: You are using pip version 22.0.4; however, version 23.2.1 is available.
  You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
  The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 9.452 seconds before retry.
  /usr/bin/docker build -t d94681:d199bc0e68d341b18937ec45bd5e3f4d -f "/home/runner/work/_actions/saadmk11/changelog-ci/v1.1.1/Dockerfile" "/home/runner/work/_actions/saadmk11/changelog-ci/v1.1.1"
  Sending build context to Docker daemon  57.34kB
  
  Step 1/14 : FROM python:3.10.5-slim-buster
   ---> 71847a102b24
  Step 2/14 : LABEL "com.github.actions.name"="Changelog CI"
   ---> Using cache
   ---> f870fbe05d86
  Step 3/14 : LABEL "com.github.actions.description"="Changelog CI is a GitHub Action that generates changelog, Then the changelog is committed and/or commented to the release Pull request."
   ---> Using cache
   ---> 7d943e09cef6
  Step 4/14 : LABEL "com.github.actions.icon"="clock"
   ---> Using cache
   ---> f8fa69fd6c7c
  Step 5/14 : LABEL "com.github.actions.color"="blue"
   ---> Using cache
   ---> 111c4c10ca90
  Step 6/14 : LABEL "repository"="https://github.com/saadmk11/changelog-ci"
   ---> Using cache
   ---> ff57dc18f44a
  Step 7/14 : LABEL "homepage"="https://github.com/saadmk11/changelog-ci"
   ---> Using cache
   ---> f3b2e7844907
  Step 8/14 : LABEL "maintainer"="saadmk11"
   ---> Using cache
   ---> eeb14ca91c4a
  Step 9/14 : RUN apt-get update     && apt-get install        -y        --no-install-recommends        --no-install-suggests        git     && apt-get clean     && rm -rf /var/lib/apt/lists/*
   ---> Using cache
   ---> 8fab4e3a7bc3
  Step 10/14 : COPY ./requirements.txt .
   ---> Using cache
   ---> c722923b71d1
  Step 11/14 : RUN pip install -r requirements.txt
   ---> Running in 33b07b08459f
  Collecting PyYAML~=5.4.1
    Downloading PyYAML-5.4.1.tar.gz (175 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 KB 34.7 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [62 lines of output]
        /tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
        !!
        
                ********************************************************************************
                The license_file parameter is deprecated, use license_files instead.
        
                By 2023-Oct-30, you need to update your project and remove deprecated calls
                or your builds will no longer be supported.
        
                See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                ********************************************************************************
        
        !!
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        running egg_info
        writing lib3/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib3/PyYAML.egg-info/top_level.txt
        Traceback (most recent call last):
          File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 271, in <module>
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
            self.find_sources()
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
            mm.run()
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
          File "<string>", line 201, in get_source_files
          File "/tmp/pip-build-env-2sqya7l4/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: You are using pip version 22.0.4; however, version 23.2.1 is available.
  You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
  The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 1.126 seconds before retry.
  /usr/bin/docker build -t d94681:d199bc0e68d341b18937ec45bd5e3f4d -f "/home/runner/work/_actions/saadmk11/changelog-ci/v1.1.1/Dockerfile" "/home/runner/work/_actions/saadmk11/changelog-ci/v1.1.1"
  Sending build context to Docker daemon  57.34kB
  
  Step 1/14 : FROM python:3.10.5-slim-buster
   ---> 71847a102b24
  Step 2/14 : LABEL "com.github.actions.name"="Changelog CI"
   ---> Using cache
   ---> f870fbe05d86
  Step 3/14 : LABEL "com.github.actions.description"="Changelog CI is a GitHub Action that generates changelog, Then the changelog is committed and/or commented to the release Pull request."
   ---> Using cache
   ---> 7d943e09cef6
  Step 4/14 : LABEL "com.github.actions.icon"="clock"
   ---> Using cache
   ---> f8fa69fd6c7c
  Step 5/14 : LABEL "com.github.actions.color"="blue"
   ---> Using cache
   ---> 111c4c10ca90
  Step 6/14 : LABEL "repository"="https://github.com/saadmk11/changelog-ci"
   ---> Using cache
   ---> ff57dc18f44a
  Step 7/14 : LABEL "homepage"="https://github.com/saadmk11/changelog-ci"
   ---> Using cache
   ---> f3b2e7844907
  Step 8/14 : LABEL "maintainer"="saadmk11"
   ---> Using cache
   ---> eeb14ca91c4a
  Step 9/14 : RUN apt-get update     && apt-get install        -y        --no-install-recommends        --no-install-suggests        git     && apt-get clean     && rm -rf /var/lib/apt/lists/*
   ---> Using cache
   ---> 8fab4e3a7bc3
  Step 10/14 : COPY ./requirements.txt .
   ---> Using cache
   ---> c722923b71d1
  Step 11/14 : RUN pip install -r requirements.txt
   ---> Running in 25847e4df47d
  Collecting PyYAML~=5.4.1
    Downloading PyYAML-5.4.1.tar.gz (175 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 KB 30.9 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [62 lines of output]
        /tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
        !!
        
                ********************************************************************************
                The license_file parameter is deprecated, use license_files instead.
        
                By 2023-Oct-30, you need to update your project and remove deprecated calls
                or your builds will no longer be supported.
        
                See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                ********************************************************************************
        
        !!
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        running egg_info
        writing lib3/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib3/PyYAML.egg-info/top_level.txt
        Traceback (most recent call last):
          File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 271, in <module>
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 314, in run
            self.find_sources()
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
            mm.run()
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
          File "<string>", line 201, in get_source_files
          File "/tmp/pip-build-env-nkno8a4r/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: You are using pip version 22.0.4; however, version 23.2.1 is available.
  You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
  The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
  
Error: Docker build failed with exit code 1
##[debug]System.InvalidOperationException: Docker build failed with exit code 1
```

**Comment by saadmk11** [comment] 2023-08-06 09:29
This should be fixed in https://github.com/saadmk11/changelog-ci/releases/tag/v1.1.2

**Comment by saadmk11** [comment] 2023-08-06 09:32
Closing this as a duplicate of https://github.com/saadmk11/changelog-ci/issues/99

Feel free to re-open it if the issue persists after updating to the latest version `v1.1.2`

**Closed by saadmk11** 2023-08-06 09:32 UTC

**Comment by tomer-ds** [comment] 2023-08-06 10:03
All good now... 
Many thanks and keep up the great work!!! 🙏
